### PR TITLE
Fix initial setup 

### PR DESCRIPTION
**Pull request by MABYY**
# Description

- Why was this work done?  The seeds were not running properly 
- What work was done? 
   -   change fields on the subission.js seeds
   - delete Admin.js file because the table does not exist anymore

### CODE REVIEW

**Review by Bus42 — COMMENTED** [review]
I noticed that the fields in submissions(X) don't share the same casing. Some are upper camel case, whereas others are lower camel case. Will that inconsistency cause any problems with the functions that consume them?

**Review by markporo — APPROVED** [review]
Good work.  Looks like these are necessary changes for seeding in the backend.  I don't think the casing will be an issue, but if you want to fix that before this is merged as Greg is suggesting then go ahead and do that.

**Review by markporo — COMMENTED** [review]
Actually...I'm not sure what Greg is referring to.  The main point of this pr is to fix the casing.  Looks to me like all of the new casing is consistent.

**Review by AaronGabriel147 — APPROVED** [review]
Looks good Maby, great job!

**Review by ashtilawat — APPROVED** [review]
Good, simple fix!

**Pull request merged**
