### PR TITLE
Feature/create notification table

### PR DESCRIPTION
**Pull request by kevinstonge**
# Description
add tables to the database for notifications, one table for parents, one table for children
Fixes #
none
- What work was done?
added two tables to the database
- Why was this work done?
new functionality (notification feature)
- What feature / user story is it for?
notification bot
- Any relevant links or images / screenshots
no
## Type of change

Please delete options that are not relevant.

- [*] New feature (non-breaking change which adds functionality)
- [*] This change requires a documentation update

## Change Status
- [*] Complete, but not tested (may need new tests)
(tested only to the extent that the knex migration file runs successfully)
- [*] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested
- [~] Yes
- [*] No
(see above)

## Checklist

- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [*] My code has been reviewed by at least one peer
- [*] I have commented my code, particularly in hard-to-understand areas
- [NO] I have made corresponding changes to the documentation
- [*] My changes generate no new warnings
- [no] I have added tests that prove my fix is effective or that my feature works
- [all tests currently running as .skip, haven't run any yet] New and existing unit tests pass locally with my changes
- [*] There are no merge conflicts

### CODE REVIEW

**Comment by devandapaige** [comment]
I'm glad we were able to help you find a solution for the instances of all parents and all students.

**Review by devandapaige — APPROVED** [review]
Looks exactly like we discussed in our last meeting. This should set us up for all of our other user stories too, which should save some time.

**Review by Johnjohnn — APPROVED** [review]
Good Job, that looks pretty good :)  Please let me know if I can help!

**Review by Bradleydion — APPROVED** [review]
Glad we could work as a team an talk through it. Looks good, and should set us up nicely for future tests and tasks.

**Review by MichelleCCodes — APPROVED** [review]

**Pull request merged**
