### PR TITLE
Feature/get episode content

### PR DESCRIPTION
**Pull request by KyleCardwell**
…esByStoryID

# Description

Fixes #

- What work was done? Episode Content was added to the response of the getEpisodeByID and getEpisodeByStoryID queries
- Why was this work done? Content was added to the Episode table, but it wasn't added to the queries
- What feature / user story is it for? https://trello.com/c/4liJQTnt/818-as-a-reader-i-want-a-more-interactive-reading-experience-so-that-i-can-stay-engaged-with-the-story
- Any relevant links or images / screenshots

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## Change Status

- [X] Complete, but not tested (may need new tests)

## Has This Been Tested

- [ ] Yes
- [X] No
- [ ] Not necessary

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

Loom Video Description: https://www.loom.com/share/976004e5c2f948ce98d1a33860e19e53

### CODE REVIEW

**Review by mattcasey879 — DISMISSED** [review]
Good Catch!

**Review by IsaacGHoward — APPROVED** [review]
Looks good to me, seems like an oversight on my end when I created that original PR and forgot to do this

**Review by ashtilawat — CHANGES_REQUESTED** [review]
Why were 8000+ lines of code deleted from the package-lock? Was this supposed to be a part of your commit? If not, please rebase.

**Comment by IsaacGHoward** [comment]
> Why were 8000+ lines of code deleted from the package-lock? Was this supposed to be a part of your commit? If not, please rebase.

Good catch I didn't even see that

**Review by IsaacGHoward — CHANGES_REQUESTED** [review]
Can't approve due to package-lock.json deletions

**Comment by ryan-hamblin** [comment]
In the event that you were actually trying to remove a package or two from the dependency tree then it would make sense for the `package.lock` file to show the removal of that dependency map. 

Did you remove something from the deps and run `npm i` at any point? 

@ashtilawat23 they may have intended to actually update that lock file.

**Comment by KyleCardwell** [comment]
Thanks for the catch!  I removed the package-lock from the PR.  Let me know if there's another fix before it gets merged

**Comment by tinomen** [comment]
Did you intend to leave `…esByStoryID` in your PR description? If, so why?

**Review by IsaacGHoward — APPROVED** [review]

**Review by victoriatrac — APPROVED** [review]
Looks good, nice job fixing the package-lock issue

**Review by ashtilawat — APPROVED** [review]

**Pull request merged**
