### PR TITLE
feature/create_gallery_submissions_table

### PR DESCRIPTION
**Pull request by jamcoding**
# Description
Created a table to track the submissions along with the week number that the child is on.

Fixes #

- What work was done?
I created a gallery_submissions table to add to the database.
- Why was this work done?
This table was created to track the child's submissions and help display track the week they are on. The front end will be able to use this information to display the recent submissions the child made.
- What feature / user story is it for?
View the recent submissions
- Any relevant links or images / screenshots
N/A

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Change Status

- [ ] Complete, but not tested (may need new tests)

## Has This Been Tested

- [ ] No

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by clarejackson — COMMENTED** [review]
This looks great! I am so glad you went with the correct spelling of Gallery. Great start for our feature! Do we know if the timestamp will work for each child in the timezone they are in?

**Comment by jamcoding** [comment]
@clarejackson It should be using the child's timezone when submitted.

**Comment by clarejackson** [comment]
Nice!! That is perfect; great job!

**Review by clarejackson — APPROVED** [review]
Nice!! That is perfect; great job!

**Review by Jet110390 — APPROVED** [review]

**Pull request merged**
