### PR TITLE
Feature/add prompts to story

### PR DESCRIPTION
**Pull request by Aaron-TheCreator**
# Description: This branch adds additional functionality to Pull Request #76 
                namely, it adds an additional function to storyNewModel.js to return both "episode prompts" (Drawing & Writing) without needing 2 functions. Episode prompts are then attached to each episode object  for a given story id. this adds additional information to the return object from the 

Fixes #76 

- What work was done?
- new function created in the model (getPromptsByEpisodeID)
- two, now redundant functions were removed from model (getDrawingByEpisodeID, getWritingByEpisodeID)
- storyNewRouter.js edited to make GET(/episodes/:eid) endpoint use getPromptsByEpisodeID function
- improperly scoped "i" variable fixed in getByID model function (storyNewModel.js)
- Why was this work done?
- this work returns a more robust object and removes the need to hit multiple endpoints to get all of the "story" data for a given ID
- What feature / user story is it for?
- https://trello.com/c/s4cxfDGf/494-add-story-prompts-to-episodes-and-return-from-the-story-id-endpoint
- Any relevant links or images / screenshots
- https://www.loom.com/share/664360d726e1441492a297276e8c6fff

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ X] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [X] No

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My code has been reviewed by at least one peer
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] There are no merge conflicts

### CODE REVIEW

**Comment by Veilios** [comment]
Everything looks great! Very clean code too.

**Review by Veilios — DISMISSED** [review]
Everything looks great! Clean code too!

**Review by Veilios — APPROVED** [review]
Everything is looking good! Clean code!

**Review by chukalicious — APPROVED** [review]
Thank you for cleaning this up and giving us a more complete object to work with!

**Pull request merged**
