### PR TITLE
Migration file created for new Audiofile column in stories table

### PR DESCRIPTION
**Pull request by kavya3v**
Created new Knex Migration file - for adding new column 'Audiofile' in the existing table "Stories". 
Note - Considering the mp4 file will be stored in the amazon s3 and the file will be seeded.

### CODE REVIEW

**Review by sunkist5691 — DISMISSED** [review]
nicely added audiofile table

**Comment by Antashma** [comment]
Your changes look good. Is that check failure what they were talking about and ok to ignore?

**Review by Antashma — DISMISSED** [review]
Ignore past comment, I see that check was failing for past merged PRs too.

**Review by kavya3v — COMMENTED** [review]
Fixed the eslint format errors

**Review by Antashma — APPROVED** [review]
Ah ok!  Didn't realize it was a linting error.  Good catch!

**Review by sunkist5691 — APPROVED** [review]

**Pull request merged**
