### PR TITLE
Response body

### PR DESCRIPTION
**Pull request by ShirleyLe3**
# Description

Fixes #

- What work was done?
Notification Response body to pass in Children information (Id, Name) for notification
- Why was this work done?
- What feature / user story is it for?
Notification for children upcoming assignments displayed onto dashboard
- Any relevant links or images / screenshots

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, but not tested (may need new tests)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by ShirleyLe3** [comment]
// Notification    message: `Welcome ${user.username}, You have ${days} to complete your ${assignment}  
  * @param {number} ID the unique ID to search the database on
  * @returns {Promise} promise that resolves to array of users with matching ID, empty if none found
  req = childId
  res = childUsername
  res = currentDayWeek      (this will be implemented on FE)

**Review by devandapaige — APPROVED** [review]
Looks like we're getting the res body that we need for the front end. There are a few linting errors in the cronTasks/notificationRouter.js. They seem like quick fixes though if there's a problem with pushing this on.

**Review by Bradleydion — APPROVED** [review]
Glad you got your pr to work. Looks good to me!!

**Comment by MichelleCCodes** [comment]
There are a few linting errors on this PR. It looks ready to be merged after these errors are resolved!

**Pull request closed without merging**
