### PR TITLE
Feature/add content to episodes

### PR DESCRIPTION
**Pull request by IsaacGHoward**
# Description
Completes the backend portion for [this user story](https://trello.com/c/E9NcMFPp/820-as-an-admin-i-want-to-upload-stories-to-the-db-so-that-i-can-manage-the-stories-and-episodes), which consisted of adding a Content column to the Episodes table, and seeding it with Lorem Ipsum 

Fixes #

- What work was done?
- Why was this work done?
- What feature / user story is it for?
  As an admin, I want to upload stories to the db so that I can manage the stories and episodes
- Any relevant links or images / screenshots
  [Trello card](https://trello.com/c/E9NcMFPp/820-as-an-admin-i-want-to-upload-stories-to-the-db-so-that-i-can-manage-the-stories-and-episodes)
  https://www.loom.com/share/06459e4fc18a43f68c629a803afb4b97

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by victoriatrac** [comment]
Looks good to me!

**Review by KyleCardwell — COMMENTED** [review]
This looks good. Nice job making the commits atomic.  They were easy to follow and understand

**Review by victoriatrac — APPROVED** [review]
Forgot to hit approve lol. But I like how thorough you were with the commits.

**Review by KyleCardwell — APPROVED** [review]
Whoops... I didn't hit approve before

**Review by Kishkuman13 — APPROVED** [review]
The code is straight forward and clean. The one bit of feedback I would offer is to trim down the description of the pull request.

**Comment by IsaacGHoward** [comment]
> The code is straight forward and clean. The one bit of feedback I would offer is to trim down the description of the pull request.

Thank you, will try to be less verbose next time.

**Comment by IsaacGHoward** [comment]
Recorded loom: https://www.loom.com/share/06459e4fc18a43f68c629a803afb4b97

**Pull request merged**
