### PR TITLE
created seed column for audiofile

### PR DESCRIPTION
**Pull request by silvodesigns**
# Description

Fixes #

- What work was done?
`I created a new property in the audio file column in the seed files to populate the database with a relative path to the audifile in front-end`
- Why was this work done?
`It was done so that the FE can pull the information seeded into the database via API call`
- What feature / user story is it for?
`As a child, I want a user-friendly media player, so that it is easy for me to use and adapt to.`
- Any relevant links or images / screenshots
`NOTE: I ALSO TEMPORARILY CHANGED THE AUDIO FILE TO NULLABLE() IN ORDER TO BYPASS THE MISSING SEED DATA. ONCE  FE CAN PULL FROM BE. I WILL RETURN TO MAKE THE COLUMN NOTNUTLLABLE() THIS IS JUST A TEMPORARY WORKAROUND`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by sunkist5691 — DISMISSED** [review]
Great description. Great job.

**Review by kevinstonge — DISMISSED** [review]
Thank you for making the change to the migration file and fixing a few linting issues. Looks good!

**Review by Antashma — DISMISSED** [review]
looks good, kevin!  Thank you for updating the audio column with the sample audio.  And thanks for fixing those linting errors.

**Review by Claeb1mb — DISMISSED** [review]
Nice Work!!

**Review by samir-hub — COMMENTED** [review]
Everything looks good. However, this PR is failing some linting checks. Please fix the lining errors described in "Test and publish test coverage".

**Review by samir-hub — APPROVED** [review]

**Review by MichelleCCodes — APPROVED** [review]

**Pull request merged**
