### PR TITLE
Auth0 error handling fix

### PR DESCRIPTION
**Pull request by kwnie**
# Description
This is to fix the error handling of the Auth0 auth required middleware. Errors were not getting caught in the middleware because it was using another instance of express. The Auth0 verification function is now in App.js where express is originally defined.

## Fixes
Moved Auth0 verification function to App.js to fix error handling

## Type of change
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by tonysorensen — COMMENTED** [review]
Nice and clean. Looks like the simple changes discussed in the meeting. For reference, for those coming later, it was a timing issue with express that was causing a problem. Moving the code fixed the problem.

**Comment by venegasgabby76** [comment]
Great job fixing this bug. Will make things a lot easier moving forward.

**Review by da-vazquez — APPROVED** [review]
Great job collaborating and coming up with a solution to this problem! This will ensure that authentication runs smoothly for the next cohort

**Review by venegasgabby76 — COMMENTED** [review]
Great job fixing this bug. Code looks clear and makes sense.

**Review by kdneldor — APPROVED** [review]
Thank you so much for this Kelsey! Looks like a good PR.

**Review by allraec — APPROVED** [review]

**Comment by allraec** [comment]
Thank you for this fix! Awesome and clean code. :)

**Comment by Aaron-TheCreator** [comment]
Thank you ! Code is clean , this PR is atomic, and you pretty much just changed the location of a function from the middleware to app.js. looks great

**Pull request merged**
