### PR TITLE
Feature/nodecron notifications scheduled days

### PR DESCRIPTION
**Pull request by kevinstonge**
# Description
created basic node-cron tasks to schedule the creation of notifications and the population of bridge tables for children users - this only applies to the daily tasks of 'read, draw, write, pointshare, vote', but the format can easily be duplicated for all notifications, or ideally refactored into a single method that accepts the properties of each notification as parameters
Fixes #

- What work was done?
added scheduling tasks
- Why was this work done?
so that notifications tables in the database could be populated automatically on a schedule
- What feature / user story is it for?
'as a student user I should receive a notification if I have a new task to complete'
- Any relevant links or images / screenshots

## Type of change

Please delete options that are not relevant.

- [*] New feature (non-breaking change which adds functionality)
- [*] This change requires a documentation update

## Change Status

- [*] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [* just a little*] Yes

## Checklist

- [*] My code follows the style guidelines of this project
- [*] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [*] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [*] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [*] New and existing unit tests pass locally with my changes
- [*] There are no merge conflicts

### CODE REVIEW

**Review by Bradleydion — DISMISSED** [review]

**Comment by Bradleydion** [comment]
Thought It was going to prompt me to leave a comment, so Ill add one here since it didn't. I see now what you were talking about in my merge request. We can discuss tomorrow during stand up. Tables look good, should be easy to manipulate should we need to for future user stories.

**Review by devandapaige — DISMISSED** [review]
Very cool. I like how you broke down the week and just have the notification text auto-populated with the `cron.schedule`. Other than the handful of testing errors, this looks like where we need to be to get the backend ready for the frontend to start using in our next round of tasks.

**Comment by devandapaige** [comment]
Yeah, @Bradleydion I hadn't considered the backend holding the text like this so easily. But with the current student notification goals we have using this scheduler seems like the easiest way to go.

**Review by MichelleCCodes — APPROVED** [review]
Great job learning how to implement node-cron! Let's definitely discuss syncing with frontend implementation tomorrow!

**Review by devandapaige — APPROVED** [review]
Awesome job fixing those pesky linting errors. Looking forward to implementing this backend soon.

**Pull request merged**
